### ISSUE TITLE
inclusion of "solidity-cli" causes many circular dependency warnings

### ISSUE THREAD

**Issue by TimDaub** [pubkey/solidity-cli#5]
Without "solidity-cli" in my code (I'm using ESM with the `.mjs` file extension):

```bash
node --version
v14.16.1
```

```bash
npm run test -- --match="*if binary is same*"

> project.bla@0.0.1 test
> ava "--match=*if binary is same*"


  if binary is same as solcli bytecode

  Rejected promise returned by test. Reason:

  ReferenceError {
    message: 'compiled is not defined',
  }

  › file://test/eth_test.mjs:11:15

  ─

  1 test failed
```

With "solidity-cli" included in my code:

```bash
npm run test -- --match="*if binary is same*"

> project.bla@0.0.1 test
> ava "--match=*if binary is same*"


(node:66193) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66193) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:66193) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
...
  if binary is same as solcli bytecode

  Rejected promise returned by test. Reason:

  ReferenceError {
    message: 'compiled is not defined',
  }

  › file://test/eth_test.mjs:11:15

  ─

  1 test failed
```

For your convenience, I added `--trace-warnings` to show you the first result:

```bash
npm run test -- --match="*if binary is same*" --node-arguments="--trace-warnings"

> bla.project@0.0.1 test
> ava "--match=*if binary is same*" "--node-arguments=--trace-warnings"


(node:68180) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object._register [as register] (/Users/user/Projects/bla.project/node_modules/shelljs/src/common.js:453:12)
    at Object.<anonymous> (/Users/user/Projects/bla.project/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .js] (/Users/user/Projects/bla.project/node_modules/ava/lib/worker/dependency-tracker.js:42:4)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**Comment by pubkey** [comment]
Can you create a repo to reproduce this?
I do not understand what you mean with `With "solidity-cli" included in my code:`
